[package]
name = "game_3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
image = "0.25.0"
winit = "0.29.15"
bevy_third_person_camera = "0.1.0"
bevy-inspector-egui = "0.23.4"
